/*
 * ===========================================================================
 *  µnleashed BBS
 *  Electronic freedom on a microcontroller.
 * ===========================================================================
 *
 * File:         src/core/helptext.h
 * Module:       Core / long help
 *
 * Purpose:      The long form of a command's help, for HELP <command> at
 *               the main prompt and /? <command> in the room. The short
 *               form stays in each Command row, where the menus need it.
 *
 *               The table is generated by tools/mkhelp.py from prose in
 *               reports/long-help-2026-09-22.md, checked on the way to fit
 *               39 columns and a C64's character set.
 *
 * Interfaces:   helptext::find
 *
 * Libraries:    none
 * Targets:      ESP32-WROOM-32E (ESP-IDF 5.3.1) and the Linux host build
 * See also:     tools/mkhelp.py
 *
 * Copyright 2026 - Robert Mech
 * License:      GNU General Public License v2 or later
 * SPDX-License-Identifier: GPL-2.0-or-later
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 2 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, see <https://www.gnu.org/licenses/>. The full
 * text is in the LICENSE file at the top of this repository.
 * ===========================================================================
 */

#pragma once

namespace helptext {

// find: the long help for a verb as typed ("WHO", "/p"), ignoring case, or
// null when there is none. The text is lines joined by '\n', the first
// being "usage: ...". Plain text: never run it through the @-code renderer,
// or the entry that explains @BELL@ rings the bell.
const char* find(const char* verb);

} // namespace helptext
