/*
 * ===========================================================================
 *  µnleashed BBS
 *  Electronic freedom on a microcontroller.
 * ===========================================================================
 *
 * File:         src/plugins/camera_brand.h
 * Module:       Plugins / camera (BBS_HAS_CAMERA boards), the wordmark
 *
 * Purpose:      The site's wordmark as a bitmap, for the bottom-left corner
 *               of a watermarked photo. GENERATED by tools/mkbrand.py from
 *               LOGO_ROWS in the directory's server.py: edit that and run
 *               the tool, never this file. 62 x 12 pixels, a bit a pixel,
 *               most significant bit on the left.
 *
 * Interfaces:   kBrandW, kBrandH, kBrand
 *
 * Libraries:    none
 * Targets:      ESP32 and ESP32-S3 camera boards and the Linux host build
 * See also:     src/plugins/camera_mark.h, tools/mkbrand.py
 *
 * Copyright 2026 - Robert Mech
 * License:      GNU General Public License v3 or later
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 3 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program. If not, see <https://www.gnu.org/licenses/>. The full
 * text is in the LICENSE file at the top of this repository.
 * ===========================================================================
 */

#pragma once
#include <cstdint>

namespace cammark {

constexpr int kBrandW = 62;
constexpr int kBrandH = 12;
constexpr uint8_t kBrand[kBrandH][8] = {
    { 0x01, 0x9B, 0x07, 0xE7, 0x8F, 0xB3, 0x7E, 0xF8 },
    { 0x01, 0x9B, 0x07, 0xEC, 0xD8, 0xB3, 0x7E, 0xCC },
    { 0xCD, 0xDB, 0x06, 0x0C, 0xD8, 0x33, 0x60, 0xCC },
    { 0xCD, 0xDB, 0x06, 0x0C, 0xD8, 0x33, 0x60, 0xCC },
    { 0xCD, 0xDB, 0x07, 0xCF, 0xCF, 0x3F, 0x7C, 0xCC },
    { 0xCD, 0xFB, 0x07, 0xCF, 0xC7, 0xBF, 0x7C, 0xCC },
    { 0xCD, 0xBB, 0x06, 0x0C, 0xC1, 0xB3, 0x60, 0xCC },
    { 0xCD, 0xBB, 0x06, 0x0C, 0xD9, 0xB3, 0x60, 0xCC },
    { 0xCD, 0xBB, 0xF7, 0xEC, 0xDF, 0x33, 0x7E, 0xCC },
    { 0xFD, 0x9B, 0xF7, 0xEC, 0xCF, 0x33, 0x7E, 0xF8 },
    { 0xC0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
    { 0xC0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
};

} // namespace cammark
