# SPDX-License-Identifier: GPL-3.0-or-later
"""
===========================================================================
 µnleashed BBS
 Electronic freedom on a microcontroller.
===========================================================================

File:         tools/mkbrand.py
Module:       Tools / the photo watermark's wordmark

Purpose:      Writes src/plugins/camera_brand.h from the site's wordmark,
              LOGO_ROWS in the directory's server.py, so the mark on a
              photo is the same drawing as the one on the site. Each text
              cell is one pixel wide and two tall: a full block lights both,
              an upper half block the top, a lower half block the bottom.

              python tools/mkbrand.py <path to unleashed_directory/server.py>

Libraries:    Python 3 standard library
Targets:      developer PC
See also:     src/plugins/camera_mark.h

Copyright 2026 - Robert Mech
License:      GNU General Public License v3 or later
SPDX-License-Identifier: GPL-3.0-or-later

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 3 of the License, or (at your
option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program. If not, see <https://www.gnu.org/licenses/>. The full
text is in the LICENSE file at the top of this repository.
===========================================================================
"""
import ast
import pathlib
import sys

FULL, UPPER, LOWER = "█", "▀", "▄"
ROOT = pathlib.Path(__file__).resolve().parent.parent


def logo_rows(server_py):
    tree = ast.parse(pathlib.Path(server_py).read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(getattr(t, "id", "") == "LOGO_ROWS" for t in node.targets):
            return ast.literal_eval(node.value)
    raise SystemExit("no LOGO_ROWS in " + server_py)


def main():
    rows = logo_rows(sys.argv[1])
    w = max(len(r) for r in rows)
    h = 2 * len(rows)
    px = [[0] * w for _ in range(h)]
    for i, row in enumerate(rows):
        for x, ch in enumerate(row):
            if ch in (FULL, UPPER):
                px[2 * i][x] = 1
            if ch in (FULL, LOWER):
                px[2 * i + 1][x] = 1
    stride = (w + 7) // 8
    lines = []
    for y in range(h):
        b = []
        for k in range(stride):
            v = 0
            for bit in range(8):
                x = k * 8 + bit
                if x < w and px[y][x]:
                    v |= 0x80 >> bit
            b.append("0x%02X" % v)
        lines.append("    { " + ", ".join(b) + " },")
    out = ROOT / "src" / "plugins" / "camera_brand.h"
    text = HEADER.format(w=w, h=h, stride=stride, rows="\n".join(lines))
    out.write_bytes(text.encode("utf-8"))
    print("wrote", out, "%dx%d" % (w, h))


HEADER = """/*
 * ===========================================================================
 *  µnleashed BBS
 *  Electronic freedom on a microcontroller.
 * ===========================================================================
 *
 * File:         src/plugins/camera_brand.h
 * Module:       Plugins / camera (BBS_HAS_CAMERA boards), the wordmark
 *
 * Purpose:      The site's wordmark as a bitmap, for the bottom-left corner
 *               of a watermarked photo. GENERATED by tools/mkbrand.py from
 *               LOGO_ROWS in the directory's server.py: edit that and run
 *               the tool, never this file. {w} x {h} pixels, a bit a pixel,
 *               most significant bit on the left.
 *
 * Interfaces:   kBrandW, kBrandH, kBrand
 *
 * Libraries:    none
 * Targets:      ESP32 and ESP32-S3 camera boards and the Linux host build
 * See also:     src/plugins/camera_mark.h, tools/mkbrand.py
 *
 * Copyright 2026 - Robert Mech
 * License:      GNU General Public License v3 or later
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 3 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program. If not, see <https://www.gnu.org/licenses/>. The full
 * text is in the LICENSE file at the top of this repository.
 * ===========================================================================
 */

#pragma once
#include <cstdint>

namespace cammark {{

constexpr int kBrandW = {w};
constexpr int kBrandH = {h};
constexpr uint8_t kBrand[kBrandH][{stride}] = {{
{rows}
}};

}} // namespace cammark
"""

if __name__ == "__main__":
    main()
