#!/usr/bin/env python3
# ===========================================================================
#  µnleashed BBS
#  Electronic freedom on a microcontroller.
# ===========================================================================
#
# File:         tools/mkhelp.py
# Module:       Build tools / long help
#
# Purpose:      Turn the long help text into src/core/helptext.cpp.
#
#               The words live in internal/long-help-2026-09-22.md, where a
#               person can read and edit them as prose with a ruler at the
#               top. This turns them into a table, so the text in the
#               firmware cannot drift from the text somebody reviewed:
#               change the prose, run this, and the table follows.
#
#               It also refuses what would be wrong on a caller's screen:
#               a line over 39 columns (a C64 wraps the 40th) and any
#               character a C64 cannot show.
#
# Usage:        python3 tools/mkhelp.py
#
# Copyright 2026 - Robert Mech
# License:      GNU General Public License v2 or later
# SPDX-License-Identifier: GPL-2.0-or-later
# ===========================================================================
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "internal" / "long-help-2026-09-22.md"
OUT = ROOT / "src" / "core" / "helptext.cpp"

NO_C64 = set("{}|~\\_^`")


def blocks(text):
    """Every help block: from a '== ' line to the first blank line."""
    out, cur = [], None
    for line in text.splitlines():
        if line.startswith("== "):
            cur = [line[3:].strip()]
            continue
        if cur is None:
            continue
        if not line.strip() or line.startswith("```"):
            out.append(cur)
            cur = None
            continue
        cur.append(line.rstrip())
    if cur:
        out.append(cur)
    return out


def check(verb, lines):
    for ln in lines:
        if len(ln) > 39:
            sys.exit(f"{verb}: over 39 columns: {ln!r}")
        bad = set(ln) & NO_C64
        if bad or any(ord(c) > 126 or ord(c) < 32 for c in ln):
            sys.exit(f"{verb}: a character a C64 cannot show: {ln!r}")
    if not lines or not lines[0].startswith("usage: "):
        sys.exit(f"{verb}: the first line must be usage:")


def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    found = blocks(SRC.read_text(encoding="utf-8"))
    seen = set()
    rows = []
    for b in found:
        verb, lines = b[0], b[1:]
        check(verb, lines)
        key = verb.upper()
        if key in seen:
            sys.exit(f"{verb}: twice")
        seen.add(key)
        body = "\\n".join(l.replace("\\", "\\\\").replace('"', '\\"') for l in lines)
        rows.append(f'    {{ {cstr(verb)}, "{body}" }},')

    OUT.write_text(
        "/*\n"
        " * ===========================================================================\n"
        " *  µnleashed BBS\n"
        " *  Electronic freedom on a microcontroller.\n"
        " * ===========================================================================\n"
        " *\n"
        " * File:         src/core/helptext.cpp\n"
        " * Module:       Core / long help\n"
        " *\n"
        " * Purpose:      GENERATED by tools/mkhelp.py from\n"
        " *               internal/long-help-2026-09-22.md. Edit the prose there and\n"
        " *               run the tool; an edit made here is lost the next time.\n"
        " *\n"
        " * Libraries:    none\n"
        " * Targets:      ESP32-WROOM-32E (ESP-IDF 5.3.1) and the Linux host build\n"
        " * See also:     helptext.h\n"
        " *\n"
        " * Copyright 2026 - Robert Mech\n"
        " * License:      GNU General Public License v2 or later\n"
        " * SPDX-License-Identifier: GPL-2.0-or-later\n"
        " * ===========================================================================\n"
        " */\n\n"
        '#include "helptext.h"\n'
        '#include "bbs_util.h"\n\n'
        "namespace helptext {\n"
        "namespace {\n\n"
        "struct Entry { const char* verb; const char* text; };\n\n"
        "// In flash, not DRAM: a const table of pointers to literals is placed\n"
        "// in .rodata, so this costs the board program space and no RAM.\n"
        "const Entry kEntries[] = {\n"
        + "\n".join(rows) + "\n"
        "};\n\n"
        "} // namespace\n\n"
        "const char* find(const char* verb) {\n"
        "    if (!verb || !*verb) return nullptr;\n"
        "    for (const Entry& e : kEntries)\n"
        "        if (bbsu::ieq(e.verb, verb)) return e.text;\n"
        "    return nullptr;\n"
        "}\n\n"
        "} // namespace helptext\n",
        encoding="utf-8")
    print(f"{OUT.relative_to(ROOT)}: {len(rows)} entries")


if __name__ == "__main__":
    main()
